#ifndef ORO_TPCC_TXN_H
#define ORO_TPCC_TXN_H

/*
 * TPC-C Transaction Profiles for oro-db.
 * Each transaction maps 1:1 to TPC-C Clause 2.4–2.8.
 */

#include "txn.h"
#include "tpcc_workload.h"
#include "tpcc_config.h"
#include "bench_util.h"

namespace oro::tpcc {

// Transaction parameter structs (pre-generated by query generator)
struct NewOrderParams {
    uint64_t w_id;
    uint64_t d_id;
    uint64_t c_id;
    uint32_t ol_cnt;
    struct OrderLine {
        uint64_t ol_i_id;
        uint64_t ol_supply_w_id;
        uint64_t ol_quantity;
    } items[MAX_OL_CNT];
    bool     all_local;
    bool     rollback;  // true if item 8191+1 triggers "not found" abort
};

struct PaymentParams {
    uint64_t w_id;
    uint64_t d_id;
    uint64_t c_w_id;
    uint64_t c_d_id;
    uint64_t c_id;        // 0 if by-name lookup
    char     c_last[17];  // used when c_id == 0
    double   h_amount;
    bool     by_last_name;
};

struct OrderStatusParams {
    uint64_t w_id;
    uint64_t d_id;
    uint64_t c_id;
    char     c_last[17];
    bool     by_last_name;
};

struct DeliveryParams {
    uint64_t w_id;
    uint64_t o_carrier_id;
};

struct StockLevelParams {
    uint64_t w_id;
    uint64_t d_id;
    uint64_t threshold;
};

// Execute each TPC-C transaction. Returns RC_OK on commit, else abort code.
MOT::RC RunNewOrder(MOT::TxnManager* txn, const TpccTables& t, const NewOrderParams& p, FastRandom& rng);
MOT::RC RunPayment(MOT::TxnManager* txn, const TpccTables& t, const PaymentParams& p);
MOT::RC RunOrderStatus(MOT::TxnManager* txn, const TpccTables& t, const OrderStatusParams& p);
MOT::RC RunDelivery(MOT::TxnManager* txn, const TpccTables& t, const DeliveryParams& p);
MOT::RC RunStockLevel(MOT::TxnManager* txn, const TpccTables& t, const StockLevelParams& p);

}  // namespace oro::tpcc
#endif  // ORO_TPCC_TXN_H
